INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It does not matter how slowly you go as long as you do not stop.','Confucius');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Either I will find a way, or I will make one.','Philip Sidney');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Motivation is what gets you started. Habit is what keeps you going.','Jim Ryun');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.','Thomas A. Edison');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Always do your best. What you plant now, you will harvest later.','Og Mandino');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.','Confucius');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Keep your eyes on the stars, and your feet on the ground.','Theodore Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You are never too old to set another goal, to dream a new dream.','C. S. Lewis');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You have to learn the rules of the game. And then you have to play better than anyone else.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t watch the clock; do what it does. Keep going.','Sam Levenson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I can''t change the direction of the wind, but I can adjust my sails to always reach my destination.','Jimmy Dean');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing is impossible, the word itself says ''I''m possible''!','Audrey Hepburn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('As we express our gratitude, we must never forget that the highest appreciation is not to utter words, but to live by them.','John F. Kennedy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The measure of who we are is what we do with what we have.','Vince Lombardi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Put your heart, mind, and soul into even your smallest acts. This is the secret of success.','Swami Sivananda');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I dwell in possibility.','Emily Dickinson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Keep your face to the sunshine and you cannot see a shadow.','Helen Keller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Believe that life is worth living and your belief will help create the fact.','William James');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Yesterday is not ours to recover, but tomorrow is ours to win or lose.','Lyndon B. Johnson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you wake up every day, you have two choices. You can either be positive or negative; an optimist or a pessimist. I choose to be an optimist. It''s all a matter of perspective.','Harvey Mackay');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You''re going to go through tough times - that''s life. But I say, ''Nothing happens to you, it happens for you.'' See the positive in negative events.','Joel Osteen');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To be beautiful means to be yourself. You don''t need to be accepted by others. You need to be yourself.','Thich Nhat Hanh');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('No matter how you feel, Get up, dress up, show up and never give up.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Believe you can and you''re halfway there.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you can imagine it, you can achieve it; if you can dream it, you can become it.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you feel like quitting, think about why you started.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Lose an hour in the morning, and you will spend all day looking for it.','Richard Whately');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I never knew a man come to greatness or eminence who lay abed late in the morning.','Johnathan Swift');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You don''t have to be great to start. But you do have to start to be great.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you feel like quitting think about why you started.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don''t build your dream, someone will hire you to help build theirs.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You may delay, but time will not.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Your life does not get better by chance, it gets better by change.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Be the change you need to see in the world.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you can dream it, you can do it.','Walt Disney');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Start where you are. Use what you have. Do what you can.','Theodore Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Set your goals high, and don''t stop till you get there.','Bo Jackson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can never quit. Winners never quit, and quitters never win.','Ted Turner');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To begin, begin.','William Wordsworth');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Only I can change my life. No one can do it for me.','Carol Burnett');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Live as if you were to die tomorrow. Learn as if you were to live forever.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t let the fear of losing be greater than the excitement of winning.','Robert Kiyosaki');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never put off till tomorrow what you can do today.','Thomas Jefferson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Stay hungry,stay foolish.','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Lose an hour in the morning, and you will be all day hunting for it.','Richard Whately');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Early to bed and early to rise, makes a man healthy, wealthy and wise.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do it now.Sometimes ''later'' becomes ''never''.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is too short, she panicked, "I want more." He nodded slowly, "Wake up earlier."','Dr. SunWolf');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The early morning has gold in its mouth.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do it badly;do it slowly;do it fearfully;do it any way you have to, but do it.','Steve Chandler');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If today were the last day of your life, would you want to do what you are about to do today?','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It''s easier to wake up early and work out than it is to look in the mirror each day and not like what you see.','Jayne Cox');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you fail to plan, you plan to fail.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Successful people are not gifted; they just work hard, then succeed on purpose.','G.K.Nielson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Ask yourself if what you''re doing today is getting you closer to where you want to be tomorrow.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('One day you will wake up and there won''t be any more time to do the things you''ve always wanted. Do it now','Paulo Coelho');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Push today for what you want tomorrow.','Lorii Myers');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is good to dream big but your dreams will never see the light of day if you sleep big too.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Live as if you were to die tomorrow, learn as if you were to live forever.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Wake up early and tackle the day before it tackles you. Be on offense, not defense.','Evan Carmichael');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Dream is not what you see in sleep dream is something which doesn''t let you sleep','A.P.J.Abdul Kalam');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I hated every minute of training, but I said, Don''t quit. Suffer now and live the rest of your life as a champion.','Muhammad Ali');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don''t wake up right now with your full might, you will never be able to achieve that dream you saw last night.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can have anything you want if you are willing to give up the belief that you can''t have it','Robert Anthony');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Opportunities will knock on your door every morning. But if you keep sleeping they will simply pass you by.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It''s not about time, it''s about choices. How are you spending your choices?','Beverly Adamo');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don''t quit.','Conrad Hilton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Even the smallest of thoughts have the potential to become the biggest of successes, all you have to do is get up and get going.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('That''s precisely the question everyone should be asking, why the hell not? Why not you? why not now?','Timothy Ferriss');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Try not to become a man of success but rather try to become a man of value.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If yesterday was an amazing day for you, don''t stop. Maybe your winning streak has just begun.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Wake up and face life''s challenges head on. Else, life will become quite a challenge.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Why complain about yesterday, when you can make a better tomorrow by making the most of today?','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every great story on the planet happened when someone decided not to give up, but kept going no matter what.','Spryte Loriano');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you haven''t been able to achieve something, today is the best time to start working towards it again.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You were born to be a player. You were meant to be here. This moment is yours.','Herb Brooks');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Even the smallest of thoughts have the potential to become the biggest of successes? all you have to do is get up and get going.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is not just another day, it is yet another chance to make your dreams come true.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Stop thinking about how much more you can sleep and start thinking about how much more you can do. Good morning.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Dude, suckin'' at something is the first step to being sorta good at something.','Jake, "Adventure Time"');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It''s your road, and yours alone.Others may walk it with you but no one can walk it for you ','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Work until your idols become your rivals','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success isn''t about being the best. It''s about always getting better.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Doubt kills more dreams than failure ever will.','Karim Seddiki');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The journey of a thousand miles begins with a single step','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is more important to know where you are going than to get there quickly. Do not mistake activity for achievement.','Isocrates');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can feel sore tomorrow or you can feel sorry tomorrow. You choose','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you fear failure, you will never go anywhere.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.','Martin Luther King Jr');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The journey is the reward.','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is not the absence of problems, it''s the ability to deal with them.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is never too late to be what you might have been.','George Eliot');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Make sure your worst enemy doesn''t live between your two ears.','Laird Hamilton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What you do today is important because you are exchanging a day of your life for it.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life begins at the end of your comfort zone.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Always be yourself, express yourself, have faith in yourself. Do not go out and look for a successful personality and duplicate it.','Bruce Lee');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Today I will do what other''s won''t, so tomorrow I will do what others can''t','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is not the load that breaks you down, It''s the way you carry it.','Lou Holtz');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Adventure may hurt you, but monotony will kill you.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t let perfection become procrastination. Do it now.','Danielle LaPorte');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You may not control all the events that happen to you, but you can decide not to be reduced by them','.Maya Angelou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is possible to commit no mistakes and still lose. That is not a weakness; that is life.','Jean Luc Picard');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In matters of style swim with the current. In matters of principle, stand like a rock.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can''t climb the ladder of success with your hands in your pockets.','Arnold Schwarzenegger');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you spend too much time thinking about a thing, you''ll never get it done.','Bruce Lee');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Winning starts with beginning.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Time you enjoy wasting is not wasted time.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('So many of our dreams at first seem impossible. Then they seem improbable. And then, when we summon the will, they soon become inevitable.','Nelson Mandela');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The creative adult is the child who survived.','Ursula K. Le Guin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do more of what makes you happy.','Carmel McConnell');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('While we are postponing, life speeds by.','Seneca');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can''t climb the ladder of success with your hands in your pockets.','Arnold Schwarzenegger');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never give up on a dream just because of the time it will take to accomplish it. The time will pass anyway.','Earl Nightingale');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Children are wonderfully confident in their own imaginations; Most of us lose this confidence as we grow up.','Sir Ken Robinson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It always seems impossible until it''s done.','Nelson Mandela');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To be free is not merely to cast off one''s chains, but to live in a way that respects and enhances the freedom of others.','Nelson Mandela');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Keep your goals away from the trolls.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('While we are postponing, life speeds by.','Seneca');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can feel sore tomorrow or you can feel sorry tomorrow. You choose.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The secret to happiness is freedom. And the secret to freedom is courage.','Thucydides');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The struggle ends when the gratitude begins.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I am strong because I''ve been weak. I am fearless because I''ve been afraid. I am wise because I''ve been foolish.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There are seven days in the week and someday isn''t one of them.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('All good things which exist are the fruits of originality','John Stuart Mill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Obsessed is a word that the lazy use to describe the dedicated.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Rules for happiness, something to do, someone to love, something to hope for.','Immanuel Kant');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The greatest mistake you can make in life is to be continually fearing you will make one.','Elbert Hubbard');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Whenever you are confronted with an opponent, conquer him with love.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Cherish your visions and your dreams as they are the children of your soul, the blueprints of your ultimate achievements.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is not the result of spontaneous combustion. You must set yourself on fire.','Reggie Leach');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Always remember that the future comes one day at a time.','Dean Acheson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is not the key to Happiness. Happiness is the key to success. If you love what you are doing, you will be successful.','Buddha');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is a state of mind. If you want success - start thinking of yourself as a success.','Dr. Joyce Brothers');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is one quality that one must possess to win, and that is definiteness of purpose, the knowledge of what one wants, and a burning desire to possess it.','Napoleon Hill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you want to succeed as much as you want to breathe, that''s when you will be successful.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Opportunity does not knock, it presents itself when you beat down the door.','Kyle Chandler');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In order to succeed, your desire for success should be greater than your fear of failure.','Bill Cosby');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you get right down to the root of the meaning of the word "succeed," you find that it simply means to follow through.','F. W. Nichol');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The successful person has the habit of doing the things failures don''t like to do. They don''t like doing them either necessarily. But their disliking is subordinated to the strength of their purpose.','E.M. Gray');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.','Mark Caine');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Often the difference between a successful person and a failure is not one has better abilities or ideas, but the courage that one has to bet on one’s ideas, to take a calculated risk – and to act.','Andre Malraux');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.','Michael Jordan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A successful man is one who can lay a firm foundation with the bricks others have thrown at him.','David Brinkley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The key to success is to focus our conscious mind on things we desire not things we fear.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success doesn’t come to you, you go to it.','Marva Collins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you want to achieve greatness stop asking for permission.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The key to success is to focus our conscious minds on things we desire, not things we fear.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success consists of going from failure to failure without loss of enthusiasm.','Winston Churchill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To guarantee success, act as if it were impossible to fail.','Dorothea Brande');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The distance between insanity and genius is measured only by success.','Bruce Feirstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The whole secret of a successful life is to find out what is one''s destiny to do, and then do it.','Henry Ford');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The only place where success comes before work is in the dictionary.','Vidal Sassoon');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People rarely succeed unless they have fun in what they are doing.','Dale Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Opportunity dances with those on the dance floor.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is the sum of small efforts, repeated day-in and day-out.','Robert Collier');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('All progress takes place outside the comfort zone.','Michael John Bobak');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Winners make a habit of manufacturing their own positive expectations in advance of the event.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Successful people do what unsuccessful people are not willing to do. Don''t wish it were easier, wish you were better.','Jim Rohn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The road to success and the road to failure are almost exactly the same.','Colin R. Davis');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The starting point of all achievement is desire.','Napolean Hill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Eighty percent of success is showing up.','Woody Allen');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The successful warrior is the average man, with laser-like focus.','Bruce Lee');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success occurs when opportunity meets preparation.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others.','John C. Maxwell');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is liking yourself, liking what you do, and liking how you do it.','Maya Angelou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Achievement is largely the product of steadily raising one''s levels of aspirations and expectation.',' Jack Nicklaus');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Action is the foundational key to all success.','Pablo Picasso');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Failure is success if we learn from it.','Malcolm Forbes');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Formal education will make you a living; self-education will make you a fortune.','Jim Rohn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you genuinely want something, don''t wait for it -- teach yourself to be impatient.','Gurbaksh Chahal');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Try not to become a person of success, but rather try to become a person of value.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy.','Tony Robbins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success does not consist in never making mistakes but in never making the same one a second time.','George Bernard Shaw');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Successful people are simply those with successful habits.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To accomplish great things, we must not only act, but also dream, not only plan, but also believe.','Anatole France');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can’t have everything you want, but you can have the things that really matter to you.','Marissa Mayer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The reason most people never reach their goals is that they don''t define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them.','Denis Watiley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Definiteness of purpose is the starting point of all achievement.','W. Clement Stone');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you set your goals ridiculously high and it''s a failure, you will fail above everyone else''s success.','James Cameron');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('One does not discover new lands without consenting to lose sight of the shore for a very long time.','Andre Gide');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Strive not to be a success, but rather to be of value.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you always do what interests you, at least one person is pleased.','Katharine Hepburn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To be successful you must accept all challenges that come your way. You can''t just accept the ones you like.','Mike Gafka');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Efforts and courage are not enough without purpose and direction.','John F. Kennedy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success on any major scale requires you to accept responsibility… in the final analysis, the one quality that all successful people have… is the ability to take on responsibility.','Michael Korda');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Failures don''t plan to fail; they fail to plan.','Harvey Mackay');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People with clear, written goals, accomplish far more in a shorter period of time than people without them could ever imagine.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing truly valuable arises from ambition or from a mere sense of duty; it stems rather from love and devotion towards men and towards objective things.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.','Ray Gofort');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing in the world is more common than unsuccessful people with talent.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A champion is afraid of losing. Everyone else is afraid of winning.','Billie Jean King');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Our greatest fear should not be of failure but of succeeding at things in life that don''t really matter.','Francis Chan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The best way of learning about anything is by doing.','Richard Branson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you''ll do things differently.','Warren Buffett');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.','Marie Curie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Fortune sides with him who dares.','Virgil');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Go big or go home. Because it''s true. What do you have to lose?','Eliza Dushku');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Success is not final, failure is not fatal: it is the courage to continue that counts.','Winston Churchill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Problems are not stop signs, they are guidelines.','Robert H. Schuller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People are always blaming their circumstances for what they are. I do not believe in circumstances. The people who get on in this world are the people who get up and look for the circumstances they want, and if they cannot find them, make them.','George Bernard Shaw');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To get what you want, STOP doing what isn''t working.','Dennis Weaver');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The universe has no restrictions. You place restrictions on the universe with your expectations.','Deepak Chopra');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never let the odds keep you from doing what you know in your heart you were meant to do.','H. Jackson Brown, Jr.');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The question isn’t who is going to let me; it’s who is going to stop me.','Ayn Rand');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Anything that is successful is a series of mistakes.','Billie Armstrong');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I have learned over the years that when one’s mind is made up, this diminishes fear.','Rosa Parks');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Even if you fall on your face you’re still moving forward.','Victor Kiam');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It always seems impossible until it is done.','Nelson Mandela');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Just when the caterpillar thought the world was ending, he turned into a butterfly.','Proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Remember that not getting what you want is sometimes a wonderful stroke of luck.','Dalai Lama');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If at first you don''t succeed, try, try, try again.','William Edward Hickson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('No one can make you feel inferior without your consent.','Eleanor Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you do what you’ve always done, you’ll get what you’ve always gotten.','Tony Robbins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don’t like something, change it. If you can’t change it, change your attitude.','Maya Angelou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I have not failed. I''ve just found 10,000 ways that won''t work.','Thomas A. Edison');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What seems to us as bitter trials are often blessings in disguise.','Oscar Wilde');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Courage is resistance to fear, mastery of fear - not absense of fear.','Mark Twain');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every experience in your life is being orchestrated to teach you something you need to know to move forward.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.','Vaibhav Shah');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you can''t fly then run, if you can''t run then walk, if you can''t walk then crawl, but whatever you do you have to keep moving forward.','Martin Luther King, Jr.');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Challenges are what make life interesting and overcoming them is what makes life meaningful.','Joshua J. Marine');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In the middle of every difficulty lies opportunity.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing will ever be attempted, if all possible objections must be first overcome.','Samuel Johnson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.','Carl Bard');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It does not matter how slowly you go as long as you do not stop.','Confucius');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.','Dale Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!','T. Harv Eker');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The most common way people give up their power is by thinking they don’t have any.','Alice Walker');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all.','Dale Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.','Theodore N. Vail');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Remember that failure is an event, not a person.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The number one reason people fail in life is because they listen to their friends, family, and neighbors.','Napoleon Hill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It’s always too early to quit.','Norman Vincent Peale');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The best way to not feel hopeless is to get up and do something. Don''t wait for good things to happen to you. If you go out and make some good things happen, you will fill the world with hope, you will fill yourself with hope.','Barack Obama');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The person who says it cannot be done should not interrupt the person who is doing it.','Chinese Proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t let what you cannot do interfere with what you can do.','John R. Wooden');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If there is no struggle, there is no progress.','Frederick Douglass');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Your problem isn''t the problem. Your reaction is the problem.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Little minds are tamed and subdued by misfortune; but great minds rise above it.','Washington Irving');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you live long enough, you''ll make mistakes. But if you learn from them, you''ll be a better person.','Bill Clinton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('We must accept finite disappointment, but never lose infinite hope.','Martin Luther King, Jr.');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I didn’t fail the test. I just found 100 ways to do it wrong.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Failure is another steppingstone to greatness.','Oprah Winfrey');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What you do today can improve all your tomorrows.','Ralph Marston');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can''t expect to hit the jackpot if you don''t put a few nickels in the machine.','Flip Wilson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You are your greatest asset. Put your time, effort and money into training, grooming, and encouraging your greatest asset.','Tom Hopkins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Be miserable. Or motivate yourself. Whatever has to be done, it''s always your choice.','Wayne Dyer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I am always doing things I can''t do, that''s how I get to do them.','Pablo Picasso');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Small Opportunities are often the beginning of great achievements.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don''t design your own life plan, chances are you''ll fall into someone else''s plan. And guess what they have planned for you? Not much.','Jim Rohn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do you want to know who you are? Don''t ask. Act! Action will delineate and define you.','Thomas Jefferson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When your desires are strong enough you will appear to possess superhuman powers to achieve.','Napoleon Hill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People who are unable to motivate themselves must be content with mediocrity, no matter how impressive their other talents.','Andrew Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You become what you think about.','Earl Nightingale');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Think big and don’t listen to people who tell you it can’t be done. Life’s too short to think small.','Tim Ferriss');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You were born to win, but to be a winner, you must plan to win, prepare to win, and expect to win.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You begin by always expecting good things to happen.','Tom Hopkins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What great thing would you attempt if you knew you could not fail?','Robert Schuller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Well done is better than well said.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('All our dreams can come true if we have the courage to pursue them.','Walt Disney');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Fall seven times, stand up eight.','Japanese proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People often say that motivation doesn''t last. Well, neither does bathing - that''s why we recommend it daily.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If the wind will not serve, take to the oars.','Latin Proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Whether you think you can or you think you can''t, you''re right.','Henry Ford');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You don’t have to be great to start, but you have to start to be great.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Motivation is what gets you started. Habit is what keeps you going.','Jim Ryun');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is never too late to be what you might have been.','George Eliot');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What the mind of man can conceive and believe, it can achieve.','Napoleon Hill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never tell me the sky’s the limit when there are footprints on the moon.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never put off till tomorrow what you can do today.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The difference between winning and losing is most often not quitting.','Walt Disney');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The best time to plant a tree was 20 years ago. The second best time is now.','Chinese Proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every new day is another chance to change your life.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Motivation will almost always beat mere talent.','Norman R. Augustine');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.','Les Brown');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction.','George Lorimer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don’t judge each day by the harvest you reap but by the seeds that you plant.','Robert Louis Stevenson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Only put off until tomorrow what you are willing to die having left undone.','Pablo Picasso');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You''ve got to get up every morning with determination if you''re going to go to bed with satisfaction.','George Lorimer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you stop chasing the wrong things you give the right things a chance to catch you.','Lolly Daskal');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What''s the point of being alive if you don''t at least try to do something remarkable.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you are going through hell, keep going.','Winston Churchill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('May you live every day of your life.','Jonathan Swift');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A dream doesn''t become reality through magic; it takes sweat, determination and hard work.','Colin Powell');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.','Ella Wheeler Wilcox');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.','Jane Smiley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If something is important enough, even if the odds are against you, you should still do it.','Elon Musk');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I am not a product of my circumstances. I am a product of my decisions.','Stephen Covey');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Dream big and dare to fail.','Norman Vaughan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Winning isn’t everything, but wanting to win is.','Vince Lombardi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do what you can, where you are, with what you have.','Teddy Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('No masterpiece was ever created by a lazy artist.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Always go with your passions. Never ask yourself if it’s realistic or not.','Deepak Chopra');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The more you dream, the farther you get.','Michael Phelps');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Some people want it to happen, some wish it would happen, others make it happen.','Michael Jordan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can’t use up creativity. The more you use, the more you have.','Maya Angelou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.','Jamie Paolinetti');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Live as if you were to die tomorrow. Learn as if you were to live forever.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Two roads diverged in a wood, and I - I took the one less traveled by. And that has made all the difference.','Robert Frost (from his poem "The Road Not Taken")');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you aren’t making any mistakes, it’s a sure sign you’re playing it too safe.','John Maxwell');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You may be disappointed if you fail, but you are doomed if you don’t try. ','Beverly Sills');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Act as if what you do makes a difference. It does.','William James');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is no passion to be found in playing small—in settling for a life that is less than you are capable of living.','Nelson Mandela');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A mind troubled by doubt cannot focus on the course to victory.','Arthur Golden');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Today, you have 100% of your life left.','Tom Hopkins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I''ve found that luck is quite predictable. If you want more luck, take more chances. Be more active. Show up more often.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I am thankful for all of those who said NO to me. It’s because of them I’m doing it myself.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Your time is limited, so don''t waste it living someone else''s life.','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.','Arnold Schwarzenegger');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The two most important days in your life are the day you are born and the day you find out why.','Mark Twain');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I don''t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well.','Diane Ackerman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is our choices that show what we truly are, far more than our abilities.','J. K Rowling (from "Harry Potter and the Chamber of Secrets")');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Go confidently in the direction of your dreams.  Live the life you have imagined. ','Henry David Thoreau');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It''s not what you look at that matters, it''s what you see.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is not about finding yourself. Life is about creating yourself.','Lolly Daskal');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.','Harriet Tubman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never say anything about yourself you do not want to come true.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing is impossible, the word itself says, “I’m possible!”','Audrey Hepburn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Things work out best for those who make the best of how things work out.','John Wooden');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is not something readymade. It comes from your own actions.','Dalai Lama');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The ones who are crazy enough to think they can change the world, are the ones that do.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('One important key to success is self-confidence. An important key to self-confidence is preparation.','Arthur Ashe');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You must expect great things of yourself before you can do them.','Michael Jordan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is 10% what happens to me and 90% of how I react to it.','Charles Swindoll');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.','Audre Lorde');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every strike brings me closer to the next home run.','Babe Ruth');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Once you choose hope, anything''s possible.','Christopher Reeve');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The longer I live, the more beautiful life becomes.','Frank Lloyd Wright');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you want to lift yourself up, lift up someone else.','Booker T. Washington');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is not what happens to you that determines how far you go in life; it is what you do with what happens to you.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness cannot be traveled to, owned, earned, or worn. It is the spiritual experience of living every minute with love, grace & gratitude.','Denis Waitley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is what we make it, always has been, always will be.','Grandma Moses');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Dreaming, after all, is a form of planning.','Gloria Steinem');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you cease to dream you cease to live.','Malcolm Forbes');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The more you praise and celebrate your life, the more there is in life to celebrate.','Oprah Winfrey');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('We can''t help everyone, but everyone can help someone.','Ronald Reagan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A positive attitude causes a chain reaction of positive thoughts, events and outcomes.  It is a catalyst and it sparks extraordinary results.','Wade Boggs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Nothing great was ever achieved without enthusiasm.','Ralph Waldo Emerson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The purpose of our lives is to be happy.','Dalai Lama');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every moment is a fresh beginning.','T.S. Eliot');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The mind is everything. What you think you become.','Buddha');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t cry because it''s over, smile because it happened.','Dr. Seuss');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is a choice that requires effort at times. ','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('According to aerodynamic laws,  the bumblebee cannot fly.  Its body weight is not the right proportion to its wingspan. Ignoring these laws, the bee flies anyway.','M. Sainte-Lague');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I was always looking outside myself for strength and confidence, but it comes from within.  It was there all the time.','Anna Freud');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You are as amazing as you let yourself be. Let me repeat that. You are as amazing as you let yourself be.','Elizabeth Alraune');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Be patient with yourself. Self-growth is tender; it''s holy ground. There''s no greater investment.','Stephen Covey');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Blessed are those who can give without remembering and take without forgetting.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I''ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.','Maya Angelou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Outstanding people have one thing in common: an absolute sense of mission.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If your ship doesn''t come in, swim out to it!','Jonathan Winters');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The discipline of writing something down is the first step toward making it happen.','Lee Iacocca');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The meeting of preparation with opportunity generates the offspring we call luck.','Anthony Robbins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Opportunity is missed by most people because it is dressed in overalls and looks like work.','Thomas A Edison');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Choose a job you love, and you will never have to work a day in your life.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Getting fired is nature''s way of telling you that you had the wrong job in the first place.','Hal Lancaster');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If people like you they’ll listen to you, but if they trust you they’ll do business with you.','Zig Ziglar');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Find out what you like doing best and get someone to pay you for doing it.','Katherine Whitehorn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You''ll never please everyone, but you only have to please a few people to get an offer.','Harvey MacKay');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.','Thomas J. Watson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Whenever you are asked if you can do a job, tell ‘em, ‘Certainly I can!’ Then get busy and find out how to do it.','Theodore Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Big jobs usually go to the men who prove their ability to outgrow small ones.','Ralph Waldo Emerson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Those who do not learn from history are doomed to repeat it.','George Santayana');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When one door closes, another opens; but we often look so long and so regretfully upon the closed door that we do not see the one which has  opened for us.','Alexander Graham Bell');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The results you achieve will be in direct proportion to the effort you apply.','Dennis Waitley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What you have to do and the way you have to do it is incredibly simple. Whether you are willing to do it is another matter.','Peter Drucker');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you do what you always did, you will get what you always got.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don''t value your time, neither will others. Stop giving away your time and talents- start charging for it.','Kim Garst');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Pearls don’t lie on the seashore. If you want one, you must dive for it.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Opportunities don''t happen, you create them.','Chris Grosser');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can''t please everyone, and you can''t make everyone like you.','Katie Couric');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t worry about failure; you only have to be right once.','Drew Houston');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t count the days, make the days count.','Muhammad Ali');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You may have to fight a battle more than once to win it.','Margaret Thatcher');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you want to be happy, set a goal that commands your thoughts, liberates your energy, and inspires your hopes.','Andrew Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Either you run the day, or the day runs you.','Jim Rohn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You never get a second chance to make a good first impression.','Will Rogers');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.','Dr. APJ Kalam');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Education costs money. But then so does ignorance.','Sir Claus Moser');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others.','Audrey Hepburn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The only way to do great work is to love what you do. If you haven''t found it yet, keep looking. Don''t settle.','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Go where you are celebrated—not tolerated. If they can''t see the real value of you, it''s time for a new start.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When written in Chinese, the word "crisis" is composed of two characters. One represents danger and the other represents opportunity.','John F. Kennedy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You miss 100% of the shots you don’t take.','Wayne Gretzky');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Only those who dare to fail greatly can ever achieve greatly.','Robert F. Kennedy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Go out on a limb. That’s where the fruit is.','Jimmy Carter');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is only one way to avoid criticism: do nothing, say nothing, and be nothing.','Aristotle');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you’re going to be thinking anything, you might as well think big.','Donald Trump');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Leap and the net will appear.','Zen Saying');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do one thing every day that scares you.','Eleanor Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is inherently risky. There is only one big risk you should avoid at all costs, and that is the risk of doing nothing.','Denis Waitley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you are not willing to risk the unusual, you will have to settle for the ordinary.','Jim Rohn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If things seem under control, you are just not going fast enough.','Mario Andretti');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A ship in harbor is safe, but that is not what ships are built for.','John A. Shedd');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Only those who play win. Only those who risk win. History favors risk-takers. Forgets the timid. Everything else is commentary.','Iveta Cherneva');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Only those who will risk going too far can possibly find out how far one can go.','T. S. Eliot');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When you take risks you learn that there will be times when you succeed and there will be times when you fail, and both are equally important.','Ellen DeGeneres');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Test fast, fail fast, adjust fast.','Tom Peters');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don’t be too timid and squeamish about your actions. All life is an experiment. The more experiments you make the better.','Ralph Waldo Emerson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Everything you’ve ever wanted is on the other side of fear.','George Addair');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('99 percent of success is built on failure.','Charles Kettering');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Danger can never be overcome without taking risks.','Latin Proverb');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Yes, risk-taking is inherently failure-prone. Otherwise, it would be called ''sure-thing-taking.','Jim McMahon');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don’t worry about failures, worry about the chances you miss when you don’t even try.','Jack Canfield');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Necessity is the mother of taking chances.','Mark Twain');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Progress always involves risks. You can''t steal second base and keep your foot on first.','Frederick Wilcox');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('People who don''t take risks generally make about two big mistakes a year. People who do take risks generally make about two big mistakes a year.','Peter Drucker');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To dare is to lose one''s footing momentarily. To not dare is to lose oneself.','Soren Kierkegaard');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t be afraid to take a big step. You can''t cross a chasm in two small jumps.','David Lloyd George');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Take calculated risks. That is quite different from being rash.','General George Patton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A person who never made a mistake never tried anything new.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t be afraid to give up the good to go for the great.','John D. Rockefeller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A man would do nothing, if he waited until he could do it so well that no one would find fault with what he has done.','Cardinal Newman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t let the fear of striking out hold you back.','Babe Ruth');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.','Booker T. Washington');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You must do the things you think you cannot do.','Eleanor Roosevelt');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If it''s a good idea, go ahead and do it. It''s much easier to apologize than it is to get permission. ','Rear Admiral Grace Hopper');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t let the fear of losing be greater than the excitement of winning.','Robert Kiyosaki');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Take risks: if you win, you will be happy; if you lose, you will be wise.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you risk nothing, then you risk everything.','Geena Davis');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Do not fear mistakes. There are none.','Miles Davis');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The dangers of life are infinite, and among them is safety.','Goethe');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Trust your own instinct. Your mistakes might as well be your own, instead of someone else’s.','Billy Wilder');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is impossible to live without failing at something, unless you live so cautiously that you might has well not have lived at all, in which case you have failed by default.','J.K. Rowling');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.','Anais Nin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is only in adventure that some people succeed in knowing themselves.','Andre Gide');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Failure is the condiment that gives success its flavor.','Truman Capote');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Taking a new step, uttering a new word, is what people fear most.','Fyodor Dostoevsky');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Too many of us are not living our dreams because we are living our fears.','Les Brown');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It often requires more courage to dare to do right than to fear to do wrong.','Abraham Lincoln');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The biggest risk is not taking any risk... In a world that''s changing really quickly, the only strategy that is guaranteed to fail is not taking risks.','Mark Zuckerberg');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To live a creative life, we must lose our fear of being wrong.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If it scares you, it might be a good thing to try.','Seth Godin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I would rather die of passion than of boredom.','Vincent van Gogh');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('When I let go of what I am, I become what I might be.','Lao Tzu');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('But you have to do what you dream of doing even while you''re afraid.','Arianna Huffington');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The function of leadership is to produce more leaders, not more followers.','Ralph Nader');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Innovation distinguishes between a leader and a follower.','Steve Jobs');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The best reason to start an organization is to make meaning; to create a product or service to make the world a better place.','Guy Kawasaki');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('As we look ahead into the next century, leaders will be those who empower others.','Bill Gates');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If your actions inspire others to dream more, learn more, do more and become more, you are a leader.','John Quincy Adams');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Become the kind of leader that people would follow voluntarily; even if you had no title or position.','Brian Tracy');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The supreme quality of leadership is integrity.','Dwight Eisenhower');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The growth and development of people is the highest calling of leadership.','Harvey Firestone');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('"Unless you are willing to drench yourself in your work beyond the capacity of the average man, you are just not cut out for positions at the top.','J.C. Penney');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you don’t build your dream, someone else will hire you to help them build theirs.','Dhirubhai Ambani');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In order to be irreplaceable one must always be different.','Coco Chanel');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The price of greatness is responsibility.','Winston Churchill');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A leader is one who see more than others see,  who sees farther than others see, and who sees before others see. ','Leroy Eims');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('He that would govern others, first should be the master of himself. ','Philip Massinger');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You only live once, but if you do it right, once is enough.','Mae West');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t raise your voice, improve your argument.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You can only be as good as you dare to be bad.','John Barrymore');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.','Sheryl Sandberg');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Genius is one per cent inspiration, ninety-nine per cent perspiration.','Thomas A Edison');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you can''t explain it simply, you don''t understand it well enough.','Albert Einstein');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I’m a great believer in luck, and I find the harder I work, the more I have of it.','Thomas Jefferson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Good things come to people who wait, but better things come to those who go out and get them.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The best revenge is massive success.','Frank Sinatra');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is no try; only do or do not.','Yoda');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Don''t take life too seriously. You''ll never get out alive.','Bugs Bunny');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I know this defies the law of gravity, but I never studied law!','Bugs Bunny');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('You get what you settle for.','Thelma and Louise');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.','Anonymous');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Screw it, Let’s do it!','Richard Branson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I believe every human has a finite number of heartbeats. I don''t intend to waste any of mine.','Neil Armstrong');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Be yourself. Everyone else is already taken.','Oscar Wilde');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Everything has beauty, but not everyone can see.','Confucius');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There are no traffic jams along the extra mile.','Roger Staubach');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I never take advice from anyone more messed up than I am.','Tom Hopkins');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Trust, but verify.','Ronald Reagan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Whenever you find yourself on the side of the majority, it is time to pause and reflect.','Mark Twain');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Remember, a dead fish can float down a stream, but it takes a live one to swim upstream.','W.C. Fields');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is being on the wire, everything else is just waiting.','Karl Wallenda');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The way I see it, if you want the rainbow, you gotta put up with the rain.','Dolly Parton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life is short, and it is here to be lived.','Kate Winslet');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Either write something worth reading or do something worth writing.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Let us always meet each other with smile, for the smile is the beginning of love.','Mother Teresa');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is when the other person''s happiness is more important than your own.','H. Jackson Brown, Jr.');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Keep love in your heart. A life without it is like a sunless garden when the flowers are dead.','Oscar Wilde');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.','Lao Tzu');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A kiss is a lovely trick designed by nature to stop speech when words become superfluous.','Ingrid Bergman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('A flower cannot blossom without sunshine, and man cannot live without love.','Max Muller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is composed of a single soul inhabiting two bodies.','Aristotle');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('We loved with a love that was more than love.','Edgar Allan Poe');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love doesn''t make the world go ''round. Love is what makes the ride worthwhile.','Franklin P. Jones');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love isn''t something you find. Love is something that finds you.','Loretta Young');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Life without love is like a tree without blossoms or fruit.','Khalil Gibran');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is no remedy for love but to love more.','Henry David Thoreau');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is when he gives you a piece of your soul, that you never knew was missing.','Torquato Tasso');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is like a beautiful flower which I may not touch, but whose fragrance makes the garden a place of delight just the same.','Helen Keller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.','James A. Baldwin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The sweetest of all sounds is that of the voice of the woman we love.','Jean de la Bruyere');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is when you meet someone who tells you something new about yourself.','Andre Breton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love yourself first and everything else falls into line. You really have to love yourself to get anything done in this world.','Lucille Ball');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love takes off masks that we fear we cannot live without and know we cannot live within.','James A. Baldwin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is an emotion experienced by the many and enjoyed by the few.','George Jean Nathan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love many things, for therein lies the true strength, and whosoever loves much performs much, and can accomplish much, and what is done in love is done well.','Vincent Van Gogh');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love does not consist in gazing at each other, but in looking outward together in the same direction.','Antoine de Saint-Exupery');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is the joy of the good, the wonder of the wise, the amazement of the Gods.','Plato');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Love is of all passions the strongest, for it attacks simultaneously the head, the heart and the senses.','Lao Tzu');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Mastering others is strength. Mastering yourself is true power.','Lao Tzu');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Never go backward. Attempt, and do it with all your might. Determination is power.','Charles Simmons');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Knowledge is power','Francis Bacon');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Personality has power to uplift, power to depress, power to curse, and power to bless.','Paul Harris');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The only way to predict the future is to have power to shape the future.','Eric Hoffer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Power is like being a lady... if you have to tell people you are, you aren''t.','Margaret Thatcher');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The most common way people give up their power is by thinking they don''t have any.','Alice Walker');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Power is given only to those who dare to lower themselves and pick it up. Only one thing matters, one thing; to be able to dare!','Fyodor Dostoevsky');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('If you realized how powerful your thoughts are, you would never think a negative thought.','Peace Pilgrim');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Circumstances are beyond human control, but our conduct is in our own power.','Benjamin Disraeli');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The way to have power is to take it.','Boss Tweed');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Power concedes nothing without a demand. It never did and it never will.','Frederick Douglass');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Calmness is the cradle of power.','Josiah Gilbert Holland');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Prestige is the shadow of money and power.','C. Wright Mills');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('To achieve, you need thought. You have to know what you are doing and that''s real power.','Ayn Rand');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Silence is the ultimate weapon of power.','Charles de Gaulle');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Power is the most persuasive rhetoric.','Friedrich Schiller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What it lies in our power to do, it lies in our power not to do.','Aristotle	');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The purpose of getting power is to be able to give it away.','Aneurin Bevan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The greatest power is often simple patience.','E. Joseph Cossman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Power is dangerous unless you have humility.','Richard J. Daley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Make the best use of what is in your power, and take the rest as it happens.','Epictetus');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is when what you think, what you say, and what you do are in harmony.','Mahatma Gandhi');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is only one happiness in this life, to love and be loved.','George Sand');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is not something ready made. It comes from your own actions.','Dalai Lama');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude.','Denis Waitley');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is not how much we have, but how much we enjoy, that makes happiness.','Charles Spurgeon');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Be happy with what you have and are, be generous with both, and you won''t have to hunt for happiness.','William E. Gladstone');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness often sneaks in through a door you didn''t know you left open.','John Barrymore');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('It is not easy to find happiness in ourselves, and it is not possible to find it elsewhere.','Agnes Repplier');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is like a kiss. You must share it to enjoy it.','Bernard Meltzer');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('True happiness comes from the joy of deeds well done, the zest of creating things new.','Antoine de Saint-Exupery');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness depends upon ourselves.','Aristotle');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.','Epictetus');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness... consists in giving, and in serving others.','Henry Drummond');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is good health and a bad memory.','Ingrid Bergman');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The Constitution only gives people the right to pursue happiness. You have to catch it yourself.','Benjamin Franklin');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is not a matter of intensity but of balance, order, rhythm and harmony.','Thomas Merton');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('True happiness is... to enjoy the present, without anxious dependence upon the future.','Lucius Annaeus Seneca');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness in intelligent people is the rarest thing I know.','Ernest Hemingway');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness doesn''t depend on any external conditions, it is governed by our mental attitude.','Dale Carnegie');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness isn''t something you experience; it''s something you remember.','Oscar Levant');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is the only good. The time to be happy is now. The place to be happy is here. The way to be happy is to make others so.','Robert Green Ingersoll');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness does not lie in happiness, but in the achievement of it.','Fyodor Dostoevsky');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness makes up in height for what it lacks in length.','Robert Frost');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Satisfaction of one''s curiosity is one of the greatest sources of happiness in life.','Linus Pauling');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is like a cloud, if you stare at it long enough, it evaporates.','Sarah McLachlan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Happiness is a virtue, not its reward.','Baruch Spinoza');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('God grant me the serenity to accept the things I cannot change, the courage to change the things I can, and the wisdom to know the difference.','Reinhold Niebuhr');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Every breath we take, every step we make, can be filled with peace, joy and serenity.','Thich Nhat Hanh');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Boredom is the feeling that everything is a waste of time; serenity, that nothing is.','Thomas Szasz');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I think that the ideal space must contain elements of magic, serenity, sorcery and mystery.','Luis Barragan');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Serenity is knowing that your worst shot is still pretty good.','Johnny Miller');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The love of learning, the sequestered nooks, And all the sweet serenity of books.','Henry Wadsworth Longfellow	');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Smiling always with a never fading serenity of countenance, and flourishing in an immortal youth.','Isaac Barrow');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The final wisdom of life requires not the annulment of incongruity but the achievement of serenity within and above it.','Reinhold Niebuhr');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('There is a kind of serenity in love which is almost a paradise.','Alain Badiou');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('In struggling against anguish one never produces serenity; the struggle against anguish only produces new forms of anguish.','Simone Weil');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('Despair is the damp of hell, as joy is the serenity of heaven.','John Donne');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I would like to be George Clooney diplomatic. I just don''t have the wherewithal yet or the inner serenity.','Shia LaBeouf');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What some people interpret as brooding melancholy is serenity. I don''t feel required to grasp all the time.','David Guterson');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I wouldn''t know how to handle serenity if somebody handed it to me on a plate.','Dusty Springfield');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('I used to find that I could get mental serenity surrounded by chaos.','Alexis Knapp');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('What I really try to do is photograph people at rest, in a state of serenity.','Irving Penn');
INSERT INTO `QUOTES` (QUOTE,AUTHOR) VALUES ('The sole art that suits me is that which, rising from unrest, tends toward serenity.','Andre Gide');